use super::models::AssetCategoryCount;

#[derive(Clone, Copy)]
pub(crate) enum AssetFetchKind {
    Quote,
    DigitalDaily,
    CommoditySeries,
}

pub(crate) struct AssetDefinition {
    pub(crate) id: &'static str,
    pub(crate) code: &'static str,
    pub(crate) name: &'static str,
    pub(crate) region: &'static str,
    pub(crate) currency: &'static str,
    pub(crate) category: &'static str,
    pub(crate) fetch_kind: AssetFetchKind,
    pub(crate) alpha_symbol: Option<&'static str>,
    pub(crate) alpha_market: Option<&'static str>,
    pub(crate) alpha_function: Option<&'static str>,
    pub(crate) finnhub_symbol: Option<&'static str>,
}

type AssetCategoryMeta = (&'static str, &'static str);

pub(crate) const STOCK_CATEGORY_ITEMS: &[AssetCategoryMeta] = &[
    ("mega-cap", "stocksSectionMegaCap"),
    ("internet", "stocksSectionInternet"),
    ("semiconductors", "stocksSectionSemiconductors"),
    ("china-adr", "stocksSectionChinaAdr"),
];
pub(crate) const ETF_CATEGORY_ITEMS: &[AssetCategoryMeta] = &[
    ("broad-market", "etfSectionBroadMarket"),
    ("sectors", "etfSectionSectors"),
    ("fixed-income", "etfSectionFixedIncome"),
    ("global-thematic", "etfSectionGlobalThematic"),
];
pub(crate) const CRYPTO_CATEGORY_ITEMS: &[AssetCategoryMeta] = &[
    ("majors", "cryptoSectionMajors"),
    ("smart-contracts", "cryptoSectionSmartContracts"),
    ("payments-meme", "cryptoSectionPaymentsMeme"),
    ("infrastructure", "cryptoSectionInfrastructure"),
];
pub(crate) const FUTURES_CATEGORY_ITEMS: &[AssetCategoryMeta] = &[
    ("energy", "futuresSectionEnergy"),
    ("metals", "futuresSectionMetals"),
    ("grains", "futuresSectionGrains"),
    ("softs", "futuresSectionSofts"),
];

pub(crate) const STOCK_DEFINITIONS: &[AssetDefinition] = &[
    AssetDefinition {
        id: "aapl",
        code: "AAPL",
        name: "Apple",
        region: "United States",
        currency: "USD",
        category: "mega-cap",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("AAPL"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("AAPL"),
    },
    AssetDefinition {
        id: "msft",
        code: "MSFT",
        name: "Microsoft",
        region: "United States",
        currency: "USD",
        category: "mega-cap",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("MSFT"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("MSFT"),
    },
    AssetDefinition {
        id: "nvda",
        code: "NVDA",
        name: "NVIDIA",
        region: "United States",
        currency: "USD",
        category: "mega-cap",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("NVDA"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("NVDA"),
    },
    AssetDefinition {
        id: "amzn",
        code: "AMZN",
        name: "Amazon",
        region: "United States",
        currency: "USD",
        category: "internet",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("AMZN"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("AMZN"),
    },
    AssetDefinition {
        id: "googl",
        code: "GOOGL",
        name: "Alphabet Class A",
        region: "United States",
        currency: "USD",
        category: "internet",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("GOOGL"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("GOOGL"),
    },
    AssetDefinition {
        id: "meta",
        code: "META",
        name: "Meta Platforms",
        region: "United States",
        currency: "USD",
        category: "internet",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("META"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("META"),
    },
    AssetDefinition {
        id: "amd",
        code: "AMD",
        name: "Advanced Micro Devices",
        region: "United States",
        currency: "USD",
        category: "semiconductors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("AMD"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("AMD"),
    },
    AssetDefinition {
        id: "tsm",
        code: "TSM",
        name: "Taiwan Semiconductor ADR",
        region: "Taiwan",
        currency: "USD",
        category: "semiconductors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("TSM"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("TSM"),
    },
    AssetDefinition {
        id: "avgo",
        code: "AVGO",
        name: "Broadcom",
        region: "United States",
        currency: "USD",
        category: "semiconductors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("AVGO"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("AVGO"),
    },
    AssetDefinition {
        id: "baba",
        code: "BABA",
        name: "Alibaba ADR",
        region: "China",
        currency: "USD",
        category: "china-adr",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("BABA"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("BABA"),
    },
    AssetDefinition {
        id: "pdd",
        code: "PDD",
        name: "PDD Holdings ADR",
        region: "China",
        currency: "USD",
        category: "china-adr",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("PDD"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("PDD"),
    },
    AssetDefinition {
        id: "bidu",
        code: "BIDU",
        name: "Baidu ADR",
        region: "China",
        currency: "USD",
        category: "china-adr",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("BIDU"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("BIDU"),
    },
];

pub(crate) const ETF_DEFINITIONS: &[AssetDefinition] = &[
    AssetDefinition {
        id: "spy",
        code: "SPY",
        name: "SPDR S&P 500 ETF Trust",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("SPY"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("SPY"),
    },
    AssetDefinition {
        id: "qqq",
        code: "QQQ",
        name: "Invesco QQQ Trust",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("QQQ"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("QQQ"),
    },
    AssetDefinition {
        id: "vti",
        code: "VTI",
        name: "Vanguard Total Stock Market ETF",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("VTI"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("VTI"),
    },
    AssetDefinition {
        id: "voo",
        code: "VOO",
        name: "Vanguard S&P 500 ETF",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("VOO"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("VOO"),
    },
    AssetDefinition {
        id: "ivv",
        code: "IVV",
        name: "iShares Core S&P 500 ETF",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("IVV"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("IVV"),
    },
    AssetDefinition {
        id: "dia",
        code: "DIA",
        name: "SPDR Dow Jones Industrial Average ETF",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("DIA"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("DIA"),
    },
    AssetDefinition {
        id: "iwm",
        code: "IWM",
        name: "iShares Russell 2000 ETF",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("IWM"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("IWM"),
    },
    AssetDefinition {
        id: "schb",
        code: "SCHB",
        name: "Schwab U.S. Broad Market ETF",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("SCHB"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("SCHB"),
    },
    AssetDefinition {
        id: "vb",
        code: "VB",
        name: "Vanguard Small-Cap ETF",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("VB"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("VB"),
    },
    AssetDefinition {
        id: "splg",
        code: "SPLG",
        name: "SPDR Portfolio S&P 500 ETF",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("SPLG"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("SPLG"),
    },
    AssetDefinition {
        id: "vug",
        code: "VUG",
        name: "Vanguard Growth ETF",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("VUG"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("VUG"),
    },
    AssetDefinition {
        id: "vtv",
        code: "VTV",
        name: "Vanguard Value ETF",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("VTV"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("VTV"),
    },
    AssetDefinition {
        id: "iwb",
        code: "IWB",
        name: "iShares Russell 1000 ETF",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("IWB"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("IWB"),
    },
    AssetDefinition {
        id: "ijr",
        code: "IJR",
        name: "iShares Core S&P Small-Cap ETF",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("IJR"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("IJR"),
    },
    AssetDefinition {
        id: "itot",
        code: "ITOT",
        name: "iShares Core S&P Total U.S. Stock Market ETF",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("ITOT"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("ITOT"),
    },
    AssetDefinition {
        id: "schx",
        code: "SCHX",
        name: "Schwab U.S. Large-Cap ETF",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("SCHX"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("SCHX"),
    },
    AssetDefinition {
        id: "rsp",
        code: "RSP",
        name: "Invesco S&P 500 Equal Weight ETF",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("RSP"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("RSP"),
    },
    AssetDefinition {
        id: "mdy",
        code: "MDY",
        name: "SPDR S&P MidCap 400 ETF Trust",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("MDY"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("MDY"),
    },
    AssetDefinition {
        id: "iyy",
        code: "IYY",
        name: "iShares Dow Jones U.S. ETF",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("IYY"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("IYY"),
    },
    AssetDefinition {
        id: "acwi",
        code: "ACWI",
        name: "iShares MSCI ACWI ETF",
        region: "Global",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("ACWI"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("ACWI"),
    },
    AssetDefinition {
        id: "vt",
        code: "VT",
        name: "Vanguard Total World Stock ETF",
        region: "Global",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("VT"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("VT"),
    },
    AssetDefinition {
        id: "vwo",
        code: "VWO",
        name: "Vanguard FTSE Emerging Markets ETF",
        region: "Global",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("VWO"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("VWO"),
    },
    AssetDefinition {
        id: "vea",
        code: "VEA",
        name: "Vanguard FTSE Developed Markets ETF",
        region: "Global",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("VEA"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("VEA"),
    },
    AssetDefinition {
        id: "iefa",
        code: "IEFA",
        name: "iShares Core MSCI EAFE ETF",
        region: "Global",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("IEFA"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("IEFA"),
    },
    AssetDefinition {
        id: "efa",
        code: "EFA",
        name: "iShares MSCI EAFE ETF",
        region: "Global",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("EFA"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("EFA"),
    },
    AssetDefinition {
        id: "xlk",
        code: "XLK",
        name: "Technology Select Sector SPDR Fund",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XLK"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XLK"),
    },
    AssetDefinition {
        id: "xlf",
        code: "XLF",
        name: "Financial Select Sector SPDR Fund",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XLF"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XLF"),
    },
    AssetDefinition {
        id: "xle",
        code: "XLE",
        name: "Energy Select Sector SPDR Fund",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XLE"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XLE"),
    },
    AssetDefinition {
        id: "xlv",
        code: "XLV",
        name: "Health Care Select Sector SPDR Fund",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XLV"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XLV"),
    },
    AssetDefinition {
        id: "xli",
        code: "XLI",
        name: "Industrial Select Sector SPDR Fund",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XLI"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XLI"),
    },
    AssetDefinition {
        id: "xlp",
        code: "XLP",
        name: "Consumer Staples Select Sector SPDR Fund",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XLP"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XLP"),
    },
    AssetDefinition {
        id: "xly",
        code: "XLY",
        name: "Consumer Discretionary Select Sector SPDR Fund",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XLY"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XLY"),
    },
    AssetDefinition {
        id: "xlu",
        code: "XLU",
        name: "Utilities Select Sector SPDR Fund",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XLU"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XLU"),
    },
    AssetDefinition {
        id: "xlb",
        code: "XLB",
        name: "Materials Select Sector SPDR Fund",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XLB"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XLB"),
    },
    AssetDefinition {
        id: "xlre",
        code: "XLRE",
        name: "Real Estate Select Sector SPDR Fund",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XLRE"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XLRE"),
    },
    AssetDefinition {
        id: "xlc",
        code: "XLC",
        name: "Communication Services Select Sector SPDR Fund",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XLC"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XLC"),
    },
    AssetDefinition {
        id: "vht",
        code: "VHT",
        name: "Vanguard Health Care ETF",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("VHT"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("VHT"),
    },
    AssetDefinition {
        id: "xsd",
        code: "XSD",
        name: "SPDR S&P Semiconductor ETF",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XSD"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XSD"),
    },
    AssetDefinition {
        id: "kre",
        code: "KRE",
        name: "SPDR S&P Regional Banking ETF",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("KRE"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("KRE"),
    },
    AssetDefinition {
        id: "kbe",
        code: "KBE",
        name: "SPDR S&P Bank ETF",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("KBE"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("KBE"),
    },
    AssetDefinition {
        id: "iyr",
        code: "IYR",
        name: "iShares U.S. Real Estate ETF",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("IYR"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("IYR"),
    },
    AssetDefinition {
        id: "xhb",
        code: "XHB",
        name: "SPDR S&P Homebuilders ETF",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XHB"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XHB"),
    },
    AssetDefinition {
        id: "xbi",
        code: "XBI",
        name: "SPDR S&P Biotech ETF",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XBI"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XBI"),
    },
    AssetDefinition {
        id: "xop",
        code: "XOP",
        name: "SPDR S&P Oil & Gas Exploration & Production ETF",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XOP"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XOP"),
    },
    AssetDefinition {
        id: "tan",
        code: "TAN",
        name: "Invesco Solar ETF",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("TAN"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("TAN"),
    },
    AssetDefinition {
        id: "pbw",
        code: "PBW",
        name: "Invesco WilderHill Clean Energy ETF",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("PBW"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("PBW"),
    },
    AssetDefinition {
        id: "smh",
        code: "SMH",
        name: "VanEck Semiconductor ETF",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("SMH"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("SMH"),
    },
    AssetDefinition {
        id: "soxx",
        code: "SOXX",
        name: "iShares Semiconductor ETF",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("SOXX"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("SOXX"),
    },
    AssetDefinition {
        id: "igv",
        code: "IGV",
        name: "iShares Expanded Tech-Software Sector ETF",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("IGV"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("IGV"),
    },
    AssetDefinition {
        id: "pjp",
        code: "PJP",
        name: "Invesco Dynamic Pharmaceuticals ETF",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("PJP"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("PJP"),
    },
    AssetDefinition {
        id: "tlt",
        code: "TLT",
        name: "iShares 20+ Year Treasury Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("TLT"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("TLT"),
    },
    AssetDefinition {
        id: "lqd",
        code: "LQD",
        name: "iShares iBoxx $ Investment Grade Corporate Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("LQD"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("LQD"),
    },
    AssetDefinition {
        id: "hyg",
        code: "HYG",
        name: "iShares iBoxx $ High Yield Corporate Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("HYG"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("HYG"),
    },
    AssetDefinition {
        id: "agg",
        code: "AGG",
        name: "iShares Core U.S. Aggregate Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("AGG"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("AGG"),
    },
    AssetDefinition {
        id: "bnd",
        code: "BND",
        name: "Vanguard Total Bond Market ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("BND"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("BND"),
    },
    AssetDefinition {
        id: "ief",
        code: "IEF",
        name: "iShares 7-10 Year Treasury Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("IEF"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("IEF"),
    },
    AssetDefinition {
        id: "shy",
        code: "SHY",
        name: "iShares 1-3 Year Treasury Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("SHY"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("SHY"),
    },
    AssetDefinition {
        id: "tip",
        code: "TIP",
        name: "iShares TIPS Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("TIP"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("TIP"),
    },
    AssetDefinition {
        id: "emb",
        code: "EMB",
        name: "iShares J.P. Morgan USD Emerging Markets Bond ETF",
        region: "Global",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("EMB"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("EMB"),
    },
    AssetDefinition {
        id: "sjnk",
        code: "SJNK",
        name: "SPDR Bloomberg Short Term High Yield Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("SJNK"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("SJNK"),
    },
    AssetDefinition {
        id: "vcit",
        code: "VCIT",
        name: "Vanguard Intermediate-Term Corporate Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("VCIT"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("VCIT"),
    },
    AssetDefinition {
        id: "bndx",
        code: "BNDX",
        name: "Vanguard Total International Bond ETF",
        region: "Global",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("BNDX"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("BNDX"),
    },
    AssetDefinition {
        id: "mub",
        code: "MUB",
        name: "iShares National Muni Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("MUB"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("MUB"),
    },
    AssetDefinition {
        id: "jnk",
        code: "JNK",
        name: "SPDR Bloomberg High Yield Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("JNK"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("JNK"),
    },
    AssetDefinition {
        id: "vmbs",
        code: "VMBS",
        name: "Vanguard Mortgage-Backed Securities ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("VMBS"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("VMBS"),
    },
    AssetDefinition {
        id: "schp",
        code: "SCHP",
        name: "Schwab U.S. TIPS ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("SCHP"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("SCHP"),
    },
    AssetDefinition {
        id: "schz",
        code: "SCHZ",
        name: "Schwab U.S. Aggregate Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("SCHZ"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("SCHZ"),
    },
    AssetDefinition {
        id: "igib",
        code: "IGIB",
        name: "iShares Intermediate-Term Corporate Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("IGIB"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("IGIB"),
    },
    AssetDefinition {
        id: "blv",
        code: "BLV",
        name: "Vanguard Long-Term Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("BLV"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("BLV"),
    },
    AssetDefinition {
        id: "govt",
        code: "GOVT",
        name: "iShares U.S. Treasury Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("GOVT"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("GOVT"),
    },
    AssetDefinition {
        id: "shv",
        code: "SHV",
        name: "iShares Short Treasury Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("SHV"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("SHV"),
    },
    AssetDefinition {
        id: "vgit",
        code: "VGIT",
        name: "Vanguard Intermediate-Term Treasury ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("VGIT"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("VGIT"),
    },
    AssetDefinition {
        id: "bsv",
        code: "BSV",
        name: "Vanguard Short-Term Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("BSV"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("BSV"),
    },
    AssetDefinition {
        id: "spsb",
        code: "SPSB",
        name: "SPDR Portfolio Short Term Corporate Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("SPSB"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("SPSB"),
    },
    AssetDefinition {
        id: "usfr",
        code: "USFR",
        name: "WisdomTree Floating Rate Treasury Fund",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("USFR"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("USFR"),
    },
    AssetDefinition {
        id: "eem",
        code: "EEM",
        name: "iShares MSCI Emerging Markets ETF",
        region: "Global",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("EEM"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("EEM"),
    },
    AssetDefinition {
        id: "gld",
        code: "GLD",
        name: "SPDR Gold Shares",
        region: "Global",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("GLD"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("GLD"),
    },
    AssetDefinition {
        id: "slv",
        code: "SLV",
        name: "iShares Silver Trust",
        region: "Global",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("SLV"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("SLV"),
    },
    AssetDefinition {
        id: "kweb",
        code: "KWEB",
        name: "KraneShares CSI China Internet ETF",
        region: "China",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("KWEB"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("KWEB"),
    },
    AssetDefinition {
        id: "fxi",
        code: "FXI",
        name: "iShares China Large-Cap ETF",
        region: "China",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("FXI"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("FXI"),
    },
    AssetDefinition {
        id: "ewj",
        code: "EWJ",
        name: "iShares MSCI Japan ETF",
        region: "Japan",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("EWJ"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("EWJ"),
    },
    AssetDefinition {
        id: "ewz",
        code: "EWZ",
        name: "iShares MSCI Brazil ETF",
        region: "Brazil",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("EWZ"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("EWZ"),
    },
    AssetDefinition {
        id: "ewg",
        code: "EWG",
        name: "iShares MSCI Germany ETF",
        region: "Germany",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("EWG"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("EWG"),
    },
    AssetDefinition {
        id: "ewu",
        code: "EWU",
        name: "iShares MSCI United Kingdom ETF",
        region: "United Kingdom",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("EWU"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("EWU"),
    },
    AssetDefinition {
        id: "ewh",
        code: "EWH",
        name: "iShares MSCI Hong Kong ETF",
        region: "Hong Kong",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("EWH"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("EWH"),
    },
    AssetDefinition {
        id: "ewy",
        code: "EWY",
        name: "iShares MSCI South Korea ETF",
        region: "South Korea",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("EWY"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("EWY"),
    },
    AssetDefinition {
        id: "ewt",
        code: "EWT",
        name: "iShares MSCI Taiwan ETF",
        region: "Taiwan",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("EWT"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("EWT"),
    },
    AssetDefinition {
        id: "inda",
        code: "INDA",
        name: "iShares MSCI India ETF",
        region: "India",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("INDA"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("INDA"),
    },
    AssetDefinition {
        id: "ewa",
        code: "EWA",
        name: "iShares MSCI Australia ETF",
        region: "Australia",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("EWA"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("EWA"),
    },
    AssetDefinition {
        id: "ewc",
        code: "EWC",
        name: "iShares MSCI Canada ETF",
        region: "Canada",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("EWC"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("EWC"),
    },
    AssetDefinition {
        id: "ewl",
        code: "EWL",
        name: "iShares MSCI Switzerland ETF",
        region: "Switzerland",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("EWL"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("EWL"),
    },
    AssetDefinition {
        id: "xme",
        code: "XME",
        name: "SPDR S&P Metals & Mining ETF",
        region: "Global",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XME"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XME"),
    },
    AssetDefinition {
        id: "gdx",
        code: "GDX",
        name: "VanEck Gold Miners ETF",
        region: "Global",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("GDX"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("GDX"),
    },
    AssetDefinition {
        id: "botz",
        code: "BOTZ",
        name: "Global X Robotics & Artificial Intelligence ETF",
        region: "Global",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("BOTZ"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("BOTZ"),
    },
    AssetDefinition {
        id: "lit",
        code: "LIT",
        name: "Global X Lithium & Battery Tech ETF",
        region: "Global",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("LIT"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("LIT"),
    },
    AssetDefinition {
        id: "ura",
        code: "URA",
        name: "Global X Uranium ETF",
        region: "Global",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("URA"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("URA"),
    },
    AssetDefinition {
        id: "remx",
        code: "REMX",
        name: "VanEck Rare Earth and Strategic Metals ETF",
        region: "Global",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("REMX"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("REMX"),
    },
    AssetDefinition {
        id: "qcln",
        code: "QCLN",
        name: "First Trust NASDAQ Clean Edge Green Energy Index Fund",
        region: "Global",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("QCLN"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("QCLN"),
    },
    AssetDefinition {
        id: "icln",
        code: "ICLN",
        name: "iShares Global Clean Energy ETF",
        region: "Global",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("ICLN"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("ICLN"),
    },
    AssetDefinition {
        id: "arkk",
        code: "ARKK",
        name: "ARK Innovation ETF",
        region: "United States",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("ARKK"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("ARKK"),
    },
];

pub(crate) const CRYPTO_DEFINITIONS: &[AssetDefinition] = &[
    AssetDefinition {
        id: "btcusd",
        code: "BTC/USD",
        name: "Bitcoin",
        region: "Global",
        currency: "USD",
        category: "majors",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("BTC"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "ethusd",
        code: "ETH/USD",
        name: "Ethereum",
        region: "Global",
        currency: "USD",
        category: "majors",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("ETH"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "xrpusd",
        code: "XRP/USD",
        name: "XRP",
        region: "Global",
        currency: "USD",
        category: "majors",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("XRP"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "solusd",
        code: "SOL/USD",
        name: "Solana",
        region: "Global",
        currency: "USD",
        category: "smart-contracts",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("SOL"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "bnbusd",
        code: "BNB/USD",
        name: "BNB",
        region: "Global",
        currency: "USD",
        category: "smart-contracts",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("BNB"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "adausd",
        code: "ADA/USD",
        name: "Cardano",
        region: "Global",
        currency: "USD",
        category: "smart-contracts",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("ADA"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "dogeusd",
        code: "DOGE/USD",
        name: "Dogecoin",
        region: "Global",
        currency: "USD",
        category: "payments-meme",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("DOGE"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "ltcusd",
        code: "LTC/USD",
        name: "Litecoin",
        region: "Global",
        currency: "USD",
        category: "payments-meme",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("LTC"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "bchusd",
        code: "BCH/USD",
        name: "Bitcoin Cash",
        region: "Global",
        currency: "USD",
        category: "payments-meme",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("BCH"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "linkusd",
        code: "LINK/USD",
        name: "Chainlink",
        region: "Global",
        currency: "USD",
        category: "infrastructure",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("LINK"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "avaxusd",
        code: "AVAX/USD",
        name: "Avalanche",
        region: "Global",
        currency: "USD",
        category: "infrastructure",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("AVAX"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "dotusd",
        code: "DOT/USD",
        name: "Polkadot",
        region: "Global",
        currency: "USD",
        category: "infrastructure",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("DOT"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
];

pub(crate) const FUTURES_DEFINITIONS: &[AssetDefinition] = &[
    AssetDefinition {
        id: "wti",
        code: "WTI",
        name: "WTI Crude Oil",
        region: "Global",
        currency: "USD",
        category: "energy",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_market: None,
        alpha_function: Some("WTI"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "brent",
        code: "BRENT",
        name: "Brent Crude Oil",
        region: "Global",
        currency: "USD",
        category: "energy",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_market: None,
        alpha_function: Some("BRENT"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "natgas",
        code: "NATGAS",
        name: "Natural Gas",
        region: "Global",
        currency: "USD",
        category: "energy",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_market: None,
        alpha_function: Some("NATURAL_GAS"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "copper",
        code: "COPPER",
        name: "Copper",
        region: "Global",
        currency: "USD",
        category: "metals",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_market: None,
        alpha_function: Some("COPPER"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "aluminum",
        code: "ALUMINUM",
        name: "Aluminum",
        region: "Global",
        currency: "USD",
        category: "metals",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_market: None,
        alpha_function: Some("ALUMINUM"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "wheat",
        code: "WHEAT",
        name: "Wheat",
        region: "Global",
        currency: "USD",
        category: "grains",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_market: None,
        alpha_function: Some("WHEAT"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "corn",
        code: "CORN",
        name: "Corn",
        region: "Global",
        currency: "USD",
        category: "grains",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_market: None,
        alpha_function: Some("CORN"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "cotton",
        code: "COTTON",
        name: "Cotton",
        region: "Global",
        currency: "USD",
        category: "softs",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_market: None,
        alpha_function: Some("COTTON"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "coffee",
        code: "COFFEE",
        name: "Coffee",
        region: "Global",
        currency: "USD",
        category: "softs",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_market: None,
        alpha_function: Some("COFFEE"),
        finnhub_symbol: None,
    },
];

pub(crate) fn supported_assets() -> &'static [&'static str] {
    &["stocks", "etf", "crypto", "futures"]
}

pub(crate) fn asset_category_items(asset: &str) -> Option<&'static [AssetCategoryMeta]> {
    match asset {
        "stocks" => Some(STOCK_CATEGORY_ITEMS),
        "etf" => Some(ETF_CATEGORY_ITEMS),
        "crypto" => Some(CRYPTO_CATEGORY_ITEMS),
        "futures" => Some(FUTURES_CATEGORY_ITEMS),
        _ => None,
    }
}

pub(crate) fn definitions_for_asset(asset: &str) -> Option<&'static [AssetDefinition]> {
    match asset {
        "stocks" => Some(STOCK_DEFINITIONS),
        "etf" => Some(ETF_DEFINITIONS),
        "crypto" => Some(CRYPTO_DEFINITIONS),
        "futures" => Some(FUTURES_DEFINITIONS),
        _ => None,
    }
}

pub(crate) fn definition_by_id(asset: &str, id: &str) -> Option<&'static AssetDefinition> {
    definitions_for_asset(asset)?
        .iter()
        .find(|definition| definition.id == id)
}

pub(crate) fn category_counts(asset: &str) -> Vec<AssetCategoryCount> {
    let Some(categories) = asset_category_items(asset) else {
        return Vec::new();
    };
    let Some(definitions) = definitions_for_asset(asset) else {
        return Vec::new();
    };

    categories
        .iter()
        .map(|(category_id, label_key)| AssetCategoryCount {
            id: (*category_id).to_string(),
            label_key: (*label_key).to_string(),
            total: definitions
                .iter()
                .filter(|definition| definition.category == *category_id)
                .count(),
        })
        .collect()
}

pub(crate) fn tradingview_symbol(asset: &str, id: &str) -> Option<&'static str> {
    match (asset, id) {
        ("stocks", "aapl") => Some("NASDAQ:AAPL"),
        ("stocks", "msft") => Some("NASDAQ:MSFT"),
        ("stocks", "nvda") => Some("NASDAQ:NVDA"),
        ("stocks", "amzn") => Some("NASDAQ:AMZN"),
        ("stocks", "googl") => Some("NASDAQ:GOOGL"),
        ("stocks", "meta") => Some("NASDAQ:META"),
        ("stocks", "amd") => Some("NASDAQ:AMD"),
        ("stocks", "tsm") => Some("NYSE:TSM"),
        ("stocks", "avgo") => Some("NASDAQ:AVGO"),
        ("stocks", "baba") => Some("NYSE:BABA"),
        ("stocks", "pdd") => Some("NASDAQ:PDD"),
        ("stocks", "bidu") => Some("NASDAQ:BIDU"),
        ("etf", "spy") => Some("AMEX:SPY"),
        ("etf", "qqq") => Some("NASDAQ:QQQ"),
        ("etf", "vti") => Some("AMEX:VTI"),
        ("etf", "voo") => Some("AMEX:VOO"),
        ("etf", "ivv") => Some("AMEX:IVV"),
        ("etf", "dia") => Some("AMEX:DIA"),
        ("etf", "iwm") => Some("AMEX:IWM"),
        ("etf", "schb") => Some("AMEX:SCHB"),
        ("etf", "vb") => Some("AMEX:VB"),
        ("etf", "splg") => Some("AMEX:SPLG"),
        ("etf", "vug") => Some("AMEX:VUG"),
        ("etf", "vtv") => Some("AMEX:VTV"),
        ("etf", "iwb") => Some("AMEX:IWB"),
        ("etf", "ijr") => Some("AMEX:IJR"),
        ("etf", "itot") => Some("AMEX:ITOT"),
        ("etf", "schx") => Some("AMEX:SCHX"),
        ("etf", "rsp") => Some("AMEX:RSP"),
        ("etf", "mdy") => Some("AMEX:MDY"),
        ("etf", "iyy") => Some("AMEX:IYY"),
        ("etf", "acwi") => Some("AMEX:ACWI"),
        ("etf", "vt") => Some("AMEX:VT"),
        ("etf", "vwo") => Some("AMEX:VWO"),
        ("etf", "vea") => Some("AMEX:VEA"),
        ("etf", "iefa") => Some("AMEX:IEFA"),
        ("etf", "efa") => Some("AMEX:EFA"),
        ("etf", "xlk") => Some("AMEX:XLK"),
        ("etf", "xlf") => Some("AMEX:XLF"),
        ("etf", "xle") => Some("AMEX:XLE"),
        ("etf", "xlv") => Some("AMEX:XLV"),
        ("etf", "xli") => Some("AMEX:XLI"),
        ("etf", "xlp") => Some("AMEX:XLP"),
        ("etf", "xly") => Some("AMEX:XLY"),
        ("etf", "xlu") => Some("AMEX:XLU"),
        ("etf", "xlb") => Some("AMEX:XLB"),
        ("etf", "xlre") => Some("AMEX:XLRE"),
        ("etf", "xlc") => Some("AMEX:XLC"),
        ("etf", "vht") => Some("AMEX:VHT"),
        ("etf", "xsd") => Some("AMEX:XSD"),
        ("etf", "kre") => Some("AMEX:KRE"),
        ("etf", "kbe") => Some("AMEX:KBE"),
        ("etf", "iyr") => Some("AMEX:IYR"),
        ("etf", "xhb") => Some("AMEX:XHB"),
        ("etf", "xbi") => Some("AMEX:XBI"),
        ("etf", "xop") => Some("AMEX:XOP"),
        ("etf", "tan") => Some("NASDAQ:TAN"),
        ("etf", "pbw") => Some("NASDAQ:PBW"),
        ("etf", "tlt") => Some("NASDAQ:TLT"),
        ("etf", "lqd") => Some("AMEX:LQD"),
        ("etf", "hyg") => Some("AMEX:HYG"),
        ("etf", "agg") => Some("AMEX:AGG"),
        ("etf", "bnd") => Some("NASDAQ:BND"),
        ("etf", "ief") => Some("NASDAQ:IEF"),
        ("etf", "shy") => Some("NASDAQ:SHY"),
        ("etf", "tip") => Some("AMEX:TIP"),
        ("etf", "emb") => Some("AMEX:EMB"),
        ("etf", "sjnk") => Some("AMEX:SJNK"),
        ("etf", "vcit") => Some("NASDAQ:VCIT"),
        ("etf", "bndx") => Some("NASDAQ:BNDX"),
        ("etf", "mub") => Some("AMEX:MUB"),
        ("etf", "jnk") => Some("AMEX:JNK"),
        ("etf", "vmbs") => Some("NASDAQ:VMBS"),
        ("etf", "schp") => Some("AMEX:SCHP"),
        ("etf", "schz") => Some("AMEX:SCHZ"),
        ("etf", "igib") => Some("NASDAQ:IGIB"),
        ("etf", "blv") => Some("AMEX:BLV"),
        ("etf", "govt") => Some("AMEX:GOVT"),
        ("etf", "shv") => Some("NASDAQ:SHV"),
        ("etf", "vgit") => Some("NASDAQ:VGIT"),
        ("etf", "bsv") => Some("AMEX:BSV"),
        ("etf", "spsb") => Some("AMEX:SPSB"),
        ("etf", "usfr") => Some("AMEX:USFR"),
        ("etf", "eem") => Some("AMEX:EEM"),
        ("etf", "smh") => Some("NASDAQ:SMH"),
        ("etf", "gld") => Some("AMEX:GLD"),
        ("etf", "slv") => Some("AMEX:SLV"),
        ("etf", "kweb") => Some("AMEX:KWEB"),
        ("etf", "fxi") => Some("AMEX:FXI"),
        ("etf", "ewj") => Some("AMEX:EWJ"),
        ("etf", "ewz") => Some("AMEX:EWZ"),
        ("etf", "ewg") => Some("AMEX:EWG"),
        ("etf", "ewu") => Some("AMEX:EWU"),
        ("etf", "ewh") => Some("AMEX:EWH"),
        ("etf", "ewy") => Some("AMEX:EWY"),
        ("etf", "ewt") => Some("AMEX:EWT"),
        ("etf", "inda") => Some("BATS:INDA"),
        ("etf", "ewa") => Some("AMEX:EWA"),
        ("etf", "ewc") => Some("AMEX:EWC"),
        ("etf", "ewl") => Some("AMEX:EWL"),
        ("etf", "xme") => Some("AMEX:XME"),
        ("etf", "gdx") => Some("AMEX:GDX"),
        ("etf", "botz") => Some("NASDAQ:BOTZ"),
        ("etf", "lit") => Some("AMEX:LIT"),
        ("etf", "ura") => Some("AMEX:URA"),
        ("etf", "remx") => Some("AMEX:REMX"),
        ("etf", "qcln") => Some("NASDAQ:QCLN"),
        ("etf", "icln") => Some("NASDAQ:ICLN"),
        ("etf", "arkk") => Some("AMEX:ARKK"),
        ("crypto", "btcusd") => Some("BINANCE:BTCUSDT"),
        ("crypto", "ethusd") => Some("BINANCE:ETHUSDT"),
        ("crypto", "xrpusd") => Some("BINANCE:XRPUSDT"),
        ("crypto", "solusd") => Some("BINANCE:SOLUSDT"),
        ("crypto", "bnbusd") => Some("BINANCE:BNBUSDT"),
        ("crypto", "adausd") => Some("BINANCE:ADAUSDT"),
        ("crypto", "dogeusd") => Some("BINANCE:DOGEUSDT"),
        ("crypto", "ltcusd") => Some("BINANCE:LTCUSDT"),
        ("crypto", "bchusd") => Some("BINANCE:BCHUSDT"),
        ("crypto", "linkusd") => Some("BINANCE:LINKUSDT"),
        ("crypto", "avaxusd") => Some("BINANCE:AVAXUSDT"),
        ("crypto", "dotusd") => Some("BINANCE:DOTUSDT"),
        ("futures", "wti") => Some("TVC:USOIL"),
        ("futures", "brent") => Some("TVC:UKOIL"),
        ("futures", "natgas") => Some("NYMEX:NG1!"),
        ("futures", "copper") => Some("COMEX:HG1!"),
        ("futures", "aluminum") => Some("LME:AH1!"),
        ("futures", "wheat") => Some("CBOT:ZW1!"),
        ("futures", "corn") => Some("CBOT:ZC1!"),
        ("futures", "cotton") => Some("ICEUS:CT1!"),
        ("futures", "coffee") => Some("ICEUS:KC1!"),
        _ => None,
    }
}
