use super::models::AssetCategoryCount;

#[derive(Clone, Copy)]
pub(crate) enum AssetFetchKind {
    Quote,
    DigitalDaily,
    CommoditySeries,
}

pub(crate) struct AssetDefinition {
    pub(crate) id: &'static str,
    pub(crate) code: &'static str,
    pub(crate) name: &'static str,
    pub(crate) region: &'static str,
    pub(crate) currency: &'static str,
    pub(crate) category: &'static str,
    pub(crate) fetch_kind: AssetFetchKind,
    pub(crate) alpha_symbol: Option<&'static str>,
    pub(crate) alpha_market: Option<&'static str>,
    pub(crate) alpha_function: Option<&'static str>,
    pub(crate) finnhub_symbol: Option<&'static str>,
}

type AssetCategoryMeta = (&'static str, &'static str);

pub(crate) const STOCK_CATEGORY_ITEMS: &[AssetCategoryMeta] = &[
    ("mega-cap", "stocksSectionMegaCap"),
    ("internet", "stocksSectionInternet"),
    ("semiconductors", "stocksSectionSemiconductors"),
    ("china-adr", "stocksSectionChinaAdr"),
];
pub(crate) const ETF_CATEGORY_ITEMS: &[AssetCategoryMeta] = &[
    ("broad-market", "etfSectionBroadMarket"),
    ("sectors", "etfSectionSectors"),
    ("fixed-income", "etfSectionFixedIncome"),
    ("global-thematic", "etfSectionGlobalThematic"),
];
pub(crate) const CRYPTO_CATEGORY_ITEMS: &[AssetCategoryMeta] = &[
    ("majors", "cryptoSectionMajors"),
    ("smart-contracts", "cryptoSectionSmartContracts"),
    ("payments-meme", "cryptoSectionPaymentsMeme"),
    ("infrastructure", "cryptoSectionInfrastructure"),
];
pub(crate) const FUTURES_CATEGORY_ITEMS: &[AssetCategoryMeta] = &[
    ("energy", "futuresSectionEnergy"),
    ("metals", "futuresSectionMetals"),
    ("grains", "futuresSectionGrains"),
    ("softs", "futuresSectionSofts"),
];

pub(crate) const STOCK_DEFINITIONS: &[AssetDefinition] = &[
    AssetDefinition {
        id: "aapl",
        code: "AAPL",
        name: "Apple",
        region: "United States",
        currency: "USD",
        category: "mega-cap",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("AAPL"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("AAPL"),
    },
    AssetDefinition {
        id: "msft",
        code: "MSFT",
        name: "Microsoft",
        region: "United States",
        currency: "USD",
        category: "mega-cap",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("MSFT"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("MSFT"),
    },
    AssetDefinition {
        id: "nvda",
        code: "NVDA",
        name: "NVIDIA",
        region: "United States",
        currency: "USD",
        category: "mega-cap",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("NVDA"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("NVDA"),
    },
    AssetDefinition {
        id: "amzn",
        code: "AMZN",
        name: "Amazon",
        region: "United States",
        currency: "USD",
        category: "internet",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("AMZN"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("AMZN"),
    },
    AssetDefinition {
        id: "googl",
        code: "GOOGL",
        name: "Alphabet Class A",
        region: "United States",
        currency: "USD",
        category: "internet",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("GOOGL"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("GOOGL"),
    },
    AssetDefinition {
        id: "meta",
        code: "META",
        name: "Meta Platforms",
        region: "United States",
        currency: "USD",
        category: "internet",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("META"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("META"),
    },
    AssetDefinition {
        id: "amd",
        code: "AMD",
        name: "Advanced Micro Devices",
        region: "United States",
        currency: "USD",
        category: "semiconductors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("AMD"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("AMD"),
    },
    AssetDefinition {
        id: "tsm",
        code: "TSM",
        name: "Taiwan Semiconductor ADR",
        region: "Taiwan",
        currency: "USD",
        category: "semiconductors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("TSM"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("TSM"),
    },
    AssetDefinition {
        id: "avgo",
        code: "AVGO",
        name: "Broadcom",
        region: "United States",
        currency: "USD",
        category: "semiconductors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("AVGO"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("AVGO"),
    },
    AssetDefinition {
        id: "baba",
        code: "BABA",
        name: "Alibaba ADR",
        region: "China",
        currency: "USD",
        category: "china-adr",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("BABA"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("BABA"),
    },
    AssetDefinition {
        id: "pdd",
        code: "PDD",
        name: "PDD Holdings ADR",
        region: "China",
        currency: "USD",
        category: "china-adr",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("PDD"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("PDD"),
    },
    AssetDefinition {
        id: "bidu",
        code: "BIDU",
        name: "Baidu ADR",
        region: "China",
        currency: "USD",
        category: "china-adr",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("BIDU"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("BIDU"),
    },
];

pub(crate) const ETF_DEFINITIONS: &[AssetDefinition] = &[
    AssetDefinition {
        id: "spy",
        code: "SPY",
        name: "SPDR S&P 500 ETF Trust",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("SPY"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("SPY"),
    },
    AssetDefinition {
        id: "qqq",
        code: "QQQ",
        name: "Invesco QQQ Trust",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("QQQ"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("QQQ"),
    },
    AssetDefinition {
        id: "vti",
        code: "VTI",
        name: "Vanguard Total Stock Market ETF",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("VTI"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("VTI"),
    },
    AssetDefinition {
        id: "xlk",
        code: "XLK",
        name: "Technology Select Sector SPDR Fund",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XLK"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XLK"),
    },
    AssetDefinition {
        id: "xlf",
        code: "XLF",
        name: "Financial Select Sector SPDR Fund",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XLF"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XLF"),
    },
    AssetDefinition {
        id: "xle",
        code: "XLE",
        name: "Energy Select Sector SPDR Fund",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XLE"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XLE"),
    },
    AssetDefinition {
        id: "tlt",
        code: "TLT",
        name: "iShares 20+ Year Treasury Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("TLT"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("TLT"),
    },
    AssetDefinition {
        id: "lqd",
        code: "LQD",
        name: "iShares iBoxx $ Investment Grade Corporate Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("LQD"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("LQD"),
    },
    AssetDefinition {
        id: "hyg",
        code: "HYG",
        name: "iShares iBoxx $ High Yield Corporate Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("HYG"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("HYG"),
    },
    AssetDefinition {
        id: "eem",
        code: "EEM",
        name: "iShares MSCI Emerging Markets ETF",
        region: "Global",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("EEM"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("EEM"),
    },
    AssetDefinition {
        id: "smh",
        code: "SMH",
        name: "VanEck Semiconductor ETF",
        region: "United States",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("SMH"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("SMH"),
    },
    AssetDefinition {
        id: "gld",
        code: "GLD",
        name: "SPDR Gold Shares",
        region: "Global",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("GLD"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("GLD"),
    },
];

pub(crate) const CRYPTO_DEFINITIONS: &[AssetDefinition] = &[
    AssetDefinition {
        id: "btcusd",
        code: "BTC/USD",
        name: "Bitcoin",
        region: "Global",
        currency: "USD",
        category: "majors",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("BTC"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "ethusd",
        code: "ETH/USD",
        name: "Ethereum",
        region: "Global",
        currency: "USD",
        category: "majors",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("ETH"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "xrpusd",
        code: "XRP/USD",
        name: "XRP",
        region: "Global",
        currency: "USD",
        category: "majors",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("XRP"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "solusd",
        code: "SOL/USD",
        name: "Solana",
        region: "Global",
        currency: "USD",
        category: "smart-contracts",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("SOL"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "bnbusd",
        code: "BNB/USD",
        name: "BNB",
        region: "Global",
        currency: "USD",
        category: "smart-contracts",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("BNB"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "adausd",
        code: "ADA/USD",
        name: "Cardano",
        region: "Global",
        currency: "USD",
        category: "smart-contracts",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("ADA"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "dogeusd",
        code: "DOGE/USD",
        name: "Dogecoin",
        region: "Global",
        currency: "USD",
        category: "payments-meme",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("DOGE"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "ltcusd",
        code: "LTC/USD",
        name: "Litecoin",
        region: "Global",
        currency: "USD",
        category: "payments-meme",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("LTC"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "bchusd",
        code: "BCH/USD",
        name: "Bitcoin Cash",
        region: "Global",
        currency: "USD",
        category: "payments-meme",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("BCH"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "linkusd",
        code: "LINK/USD",
        name: "Chainlink",
        region: "Global",
        currency: "USD",
        category: "infrastructure",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("LINK"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "avaxusd",
        code: "AVAX/USD",
        name: "Avalanche",
        region: "Global",
        currency: "USD",
        category: "infrastructure",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("AVAX"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "dotusd",
        code: "DOT/USD",
        name: "Polkadot",
        region: "Global",
        currency: "USD",
        category: "infrastructure",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("DOT"),
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
];

pub(crate) const FUTURES_DEFINITIONS: &[AssetDefinition] = &[
    AssetDefinition {
        id: "wti",
        code: "WTI",
        name: "WTI Crude Oil",
        region: "Global",
        currency: "USD",
        category: "energy",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_market: None,
        alpha_function: Some("WTI"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "brent",
        code: "BRENT",
        name: "Brent Crude Oil",
        region: "Global",
        currency: "USD",
        category: "energy",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_market: None,
        alpha_function: Some("BRENT"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "natgas",
        code: "NATGAS",
        name: "Natural Gas",
        region: "Global",
        currency: "USD",
        category: "energy",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_market: None,
        alpha_function: Some("NATURAL_GAS"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "copper",
        code: "COPPER",
        name: "Copper",
        region: "Global",
        currency: "USD",
        category: "metals",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_market: None,
        alpha_function: Some("COPPER"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "aluminum",
        code: "ALUMINUM",
        name: "Aluminum",
        region: "Global",
        currency: "USD",
        category: "metals",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_market: None,
        alpha_function: Some("ALUMINUM"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "wheat",
        code: "WHEAT",
        name: "Wheat",
        region: "Global",
        currency: "USD",
        category: "grains",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_market: None,
        alpha_function: Some("WHEAT"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "corn",
        code: "CORN",
        name: "Corn",
        region: "Global",
        currency: "USD",
        category: "grains",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_market: None,
        alpha_function: Some("CORN"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "cotton",
        code: "COTTON",
        name: "Cotton",
        region: "Global",
        currency: "USD",
        category: "softs",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_market: None,
        alpha_function: Some("COTTON"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "coffee",
        code: "COFFEE",
        name: "Coffee",
        region: "Global",
        currency: "USD",
        category: "softs",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_market: None,
        alpha_function: Some("COFFEE"),
        finnhub_symbol: None,
    },
];

pub(crate) fn supported_assets() -> &'static [&'static str] {
    &["stocks", "etf", "crypto", "futures"]
}

pub(crate) fn asset_category_items(asset: &str) -> Option<&'static [AssetCategoryMeta]> {
    match asset {
        "stocks" => Some(STOCK_CATEGORY_ITEMS),
        "etf" => Some(ETF_CATEGORY_ITEMS),
        "crypto" => Some(CRYPTO_CATEGORY_ITEMS),
        "futures" => Some(FUTURES_CATEGORY_ITEMS),
        _ => None,
    }
}

pub(crate) fn definitions_for_asset(asset: &str) -> Option<&'static [AssetDefinition]> {
    match asset {
        "stocks" => Some(STOCK_DEFINITIONS),
        "etf" => Some(ETF_DEFINITIONS),
        "crypto" => Some(CRYPTO_DEFINITIONS),
        "futures" => Some(FUTURES_DEFINITIONS),
        _ => None,
    }
}

pub(crate) fn definition_by_id(asset: &str, id: &str) -> Option<&'static AssetDefinition> {
    definitions_for_asset(asset)?
        .iter()
        .find(|definition| definition.id == id)
}

pub(crate) fn category_counts(asset: &str) -> Vec<AssetCategoryCount> {
    let Some(categories) = asset_category_items(asset) else {
        return Vec::new();
    };
    let Some(definitions) = definitions_for_asset(asset) else {
        return Vec::new();
    };

    categories
        .iter()
        .map(|(category_id, label_key)| AssetCategoryCount {
            id: (*category_id).to_string(),
            label_key: (*label_key).to_string(),
            total: definitions
                .iter()
                .filter(|definition| definition.category == *category_id)
                .count(),
        })
        .collect()
}

pub(crate) fn tradingview_symbol(asset: &str, id: &str) -> Option<&'static str> {
    match (asset, id) {
        ("stocks", "aapl") => Some("NASDAQ:AAPL"),
        ("stocks", "msft") => Some("NASDAQ:MSFT"),
        ("stocks", "nvda") => Some("NASDAQ:NVDA"),
        ("stocks", "amzn") => Some("NASDAQ:AMZN"),
        ("stocks", "googl") => Some("NASDAQ:GOOGL"),
        ("stocks", "meta") => Some("NASDAQ:META"),
        ("stocks", "amd") => Some("NASDAQ:AMD"),
        ("stocks", "tsm") => Some("NYSE:TSM"),
        ("stocks", "avgo") => Some("NASDAQ:AVGO"),
        ("stocks", "baba") => Some("NYSE:BABA"),
        ("stocks", "pdd") => Some("NASDAQ:PDD"),
        ("stocks", "bidu") => Some("NASDAQ:BIDU"),
        ("etf", "spy") => Some("AMEX:SPY"),
        ("etf", "qqq") => Some("NASDAQ:QQQ"),
        ("etf", "vti") => Some("AMEX:VTI"),
        ("etf", "xlk") => Some("AMEX:XLK"),
        ("etf", "xlf") => Some("AMEX:XLF"),
        ("etf", "xle") => Some("AMEX:XLE"),
        ("etf", "tlt") => Some("NASDAQ:TLT"),
        ("etf", "lqd") => Some("AMEX:LQD"),
        ("etf", "hyg") => Some("AMEX:HYG"),
        ("etf", "eem") => Some("AMEX:EEM"),
        ("etf", "smh") => Some("NASDAQ:SMH"),
        ("etf", "gld") => Some("AMEX:GLD"),
        ("crypto", "btcusd") => Some("BINANCE:BTCUSDT"),
        ("crypto", "ethusd") => Some("BINANCE:ETHUSDT"),
        ("crypto", "xrpusd") => Some("BINANCE:XRPUSDT"),
        ("crypto", "solusd") => Some("BINANCE:SOLUSDT"),
        ("crypto", "bnbusd") => Some("BINANCE:BNBUSDT"),
        ("crypto", "adausd") => Some("BINANCE:ADAUSDT"),
        ("crypto", "dogeusd") => Some("BINANCE:DOGEUSDT"),
        ("crypto", "ltcusd") => Some("BINANCE:LTCUSDT"),
        ("crypto", "bchusd") => Some("BINANCE:BCHUSDT"),
        ("crypto", "linkusd") => Some("BINANCE:LINKUSDT"),
        ("crypto", "avaxusd") => Some("BINANCE:AVAXUSDT"),
        ("crypto", "dotusd") => Some("BINANCE:DOTUSDT"),
        ("futures", "wti") => Some("TVC:USOIL"),
        ("futures", "brent") => Some("TVC:UKOIL"),
        ("futures", "natgas") => Some("NYMEX:NG1!"),
        ("futures", "copper") => Some("COMEX:HG1!"),
        ("futures", "aluminum") => Some("LME:AH1!"),
        ("futures", "wheat") => Some("CBOT:ZW1!"),
        ("futures", "corn") => Some("CBOT:ZC1!"),
        ("futures", "cotton") => Some("ICEUS:CT1!"),
        ("futures", "coffee") => Some("ICEUS:KC1!"),
        _ => None,
    }
}
