use super::models::AssetCategoryCount;

#[derive(Clone, Copy)]
pub(crate) enum AssetFetchKind {
    Quote,
    FxDaily,
    DigitalDaily,
    CommoditySeries,
}

pub(crate) struct AssetDefinition {
    pub(crate) id: &'static str,
    pub(crate) code: &'static str,
    pub(crate) name: &'static str,
    pub(crate) region: &'static str,
    pub(crate) currency: &'static str,
    pub(crate) category: &'static str,
    pub(crate) fetch_kind: AssetFetchKind,
    pub(crate) alpha_symbol: Option<&'static str>,
    pub(crate) alpha_base: Option<&'static str>,
    pub(crate) alpha_quote: Option<&'static str>,
    pub(crate) alpha_market: Option<&'static str>,
    pub(crate) alpha_function: Option<&'static str>,
    pub(crate) finnhub_symbol: Option<&'static str>,
}

pub(crate) const STOCK_CATEGORY_IDS: &[&str] =
    &["mega-cap", "internet", "semiconductors", "china-adr"];
pub(crate) const ETF_CATEGORY_IDS: &[&str] =
    &["broad-market", "sectors", "fixed-income", "global-thematic"];
pub(crate) const CRYPTO_CATEGORY_IDS: &[&str] = &[
    "majors",
    "smart-contracts",
    "payments-meme",
    "infrastructure",
];
pub(crate) const FOREX_CATEGORY_IDS: &[&str] = &["majors", "dollar-bloc", "asia", "crosses"];
pub(crate) const FUTURES_CATEGORY_IDS: &[&str] = &["energy", "metals", "grains", "softs"];

pub(crate) const STOCK_DEFINITIONS: &[AssetDefinition] = &[
    AssetDefinition {
        id: "aapl",
        code: "AAPL",
        name: "Apple",
        region: "United States",
        currency: "USD",
        category: "mega-cap",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("AAPL"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("AAPL"),
    },
    AssetDefinition {
        id: "msft",
        code: "MSFT",
        name: "Microsoft",
        region: "United States",
        currency: "USD",
        category: "mega-cap",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("MSFT"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("MSFT"),
    },
    AssetDefinition {
        id: "nvda",
        code: "NVDA",
        name: "NVIDIA",
        region: "United States",
        currency: "USD",
        category: "mega-cap",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("NVDA"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("NVDA"),
    },
    AssetDefinition {
        id: "amzn",
        code: "AMZN",
        name: "Amazon",
        region: "United States",
        currency: "USD",
        category: "internet",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("AMZN"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("AMZN"),
    },
    AssetDefinition {
        id: "googl",
        code: "GOOGL",
        name: "Alphabet Class A",
        region: "United States",
        currency: "USD",
        category: "internet",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("GOOGL"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("GOOGL"),
    },
    AssetDefinition {
        id: "meta",
        code: "META",
        name: "Meta Platforms",
        region: "United States",
        currency: "USD",
        category: "internet",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("META"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("META"),
    },
    AssetDefinition {
        id: "amd",
        code: "AMD",
        name: "Advanced Micro Devices",
        region: "United States",
        currency: "USD",
        category: "semiconductors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("AMD"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("AMD"),
    },
    AssetDefinition {
        id: "tsm",
        code: "TSM",
        name: "Taiwan Semiconductor ADR",
        region: "Taiwan",
        currency: "USD",
        category: "semiconductors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("TSM"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("TSM"),
    },
    AssetDefinition {
        id: "avgo",
        code: "AVGO",
        name: "Broadcom",
        region: "United States",
        currency: "USD",
        category: "semiconductors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("AVGO"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("AVGO"),
    },
    AssetDefinition {
        id: "baba",
        code: "BABA",
        name: "Alibaba ADR",
        region: "China",
        currency: "USD",
        category: "china-adr",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("BABA"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("BABA"),
    },
    AssetDefinition {
        id: "pdd",
        code: "PDD",
        name: "PDD Holdings ADR",
        region: "China",
        currency: "USD",
        category: "china-adr",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("PDD"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("PDD"),
    },
    AssetDefinition {
        id: "bidu",
        code: "BIDU",
        name: "Baidu ADR",
        region: "China",
        currency: "USD",
        category: "china-adr",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("BIDU"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("BIDU"),
    },
];

pub(crate) const ETF_DEFINITIONS: &[AssetDefinition] = &[
    AssetDefinition {
        id: "spy",
        code: "SPY",
        name: "SPDR S&P 500 ETF Trust",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("SPY"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("SPY"),
    },
    AssetDefinition {
        id: "qqq",
        code: "QQQ",
        name: "Invesco QQQ Trust",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("QQQ"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("QQQ"),
    },
    AssetDefinition {
        id: "vti",
        code: "VTI",
        name: "Vanguard Total Stock Market ETF",
        region: "United States",
        currency: "USD",
        category: "broad-market",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("VTI"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("VTI"),
    },
    AssetDefinition {
        id: "xlk",
        code: "XLK",
        name: "Technology Select Sector SPDR Fund",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XLK"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XLK"),
    },
    AssetDefinition {
        id: "xlf",
        code: "XLF",
        name: "Financial Select Sector SPDR Fund",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XLF"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XLF"),
    },
    AssetDefinition {
        id: "xle",
        code: "XLE",
        name: "Energy Select Sector SPDR Fund",
        region: "United States",
        currency: "USD",
        category: "sectors",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("XLE"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("XLE"),
    },
    AssetDefinition {
        id: "tlt",
        code: "TLT",
        name: "iShares 20+ Year Treasury Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("TLT"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("TLT"),
    },
    AssetDefinition {
        id: "lqd",
        code: "LQD",
        name: "iShares iBoxx $ Investment Grade Corporate Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("LQD"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("LQD"),
    },
    AssetDefinition {
        id: "hyg",
        code: "HYG",
        name: "iShares iBoxx $ High Yield Corporate Bond ETF",
        region: "United States",
        currency: "USD",
        category: "fixed-income",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("HYG"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("HYG"),
    },
    AssetDefinition {
        id: "eem",
        code: "EEM",
        name: "iShares MSCI Emerging Markets ETF",
        region: "Global",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("EEM"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("EEM"),
    },
    AssetDefinition {
        id: "smh",
        code: "SMH",
        name: "VanEck Semiconductor ETF",
        region: "United States",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("SMH"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("SMH"),
    },
    AssetDefinition {
        id: "gld",
        code: "GLD",
        name: "SPDR Gold Shares",
        region: "Global",
        currency: "USD",
        category: "global-thematic",
        fetch_kind: AssetFetchKind::Quote,
        alpha_symbol: Some("GLD"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: Some("GLD"),
    },
];

pub(crate) const CRYPTO_DEFINITIONS: &[AssetDefinition] = &[
    AssetDefinition {
        id: "btcusd",
        code: "BTC/USD",
        name: "Bitcoin",
        region: "Global",
        currency: "USD",
        category: "majors",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("BTC"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "ethusd",
        code: "ETH/USD",
        name: "Ethereum",
        region: "Global",
        currency: "USD",
        category: "majors",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("ETH"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "xrpusd",
        code: "XRP/USD",
        name: "XRP",
        region: "Global",
        currency: "USD",
        category: "majors",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("XRP"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "solusd",
        code: "SOL/USD",
        name: "Solana",
        region: "Global",
        currency: "USD",
        category: "smart-contracts",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("SOL"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "bnbusd",
        code: "BNB/USD",
        name: "BNB",
        region: "Global",
        currency: "USD",
        category: "smart-contracts",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("BNB"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "adausd",
        code: "ADA/USD",
        name: "Cardano",
        region: "Global",
        currency: "USD",
        category: "smart-contracts",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("ADA"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "dogeusd",
        code: "DOGE/USD",
        name: "Dogecoin",
        region: "Global",
        currency: "USD",
        category: "payments-meme",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("DOGE"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "ltcusd",
        code: "LTC/USD",
        name: "Litecoin",
        region: "Global",
        currency: "USD",
        category: "payments-meme",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("LTC"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "bchusd",
        code: "BCH/USD",
        name: "Bitcoin Cash",
        region: "Global",
        currency: "USD",
        category: "payments-meme",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("BCH"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "linkusd",
        code: "LINK/USD",
        name: "Chainlink",
        region: "Global",
        currency: "USD",
        category: "infrastructure",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("LINK"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "avaxusd",
        code: "AVAX/USD",
        name: "Avalanche",
        region: "Global",
        currency: "USD",
        category: "infrastructure",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("AVAX"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "dotusd",
        code: "DOT/USD",
        name: "Polkadot",
        region: "Global",
        currency: "USD",
        category: "infrastructure",
        fetch_kind: AssetFetchKind::DigitalDaily,
        alpha_symbol: Some("DOT"),
        alpha_base: None,
        alpha_quote: None,
        alpha_market: Some("USD"),
        alpha_function: None,
        finnhub_symbol: None,
    },
];

pub(crate) const FOREX_DEFINITIONS: &[AssetDefinition] = &[
    AssetDefinition {
        id: "eurusd",
        code: "EUR/USD",
        name: "Euro / US Dollar",
        region: "Global",
        currency: "USD",
        category: "majors",
        fetch_kind: AssetFetchKind::FxDaily,
        alpha_symbol: None,
        alpha_base: Some("EUR"),
        alpha_quote: Some("USD"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "gbpusd",
        code: "GBP/USD",
        name: "British Pound / US Dollar",
        region: "Global",
        currency: "USD",
        category: "majors",
        fetch_kind: AssetFetchKind::FxDaily,
        alpha_symbol: None,
        alpha_base: Some("GBP"),
        alpha_quote: Some("USD"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "usdjpy",
        code: "USD/JPY",
        name: "US Dollar / Japanese Yen",
        region: "Japan",
        currency: "JPY",
        category: "majors",
        fetch_kind: AssetFetchKind::FxDaily,
        alpha_symbol: None,
        alpha_base: Some("USD"),
        alpha_quote: Some("JPY"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "audusd",
        code: "AUD/USD",
        name: "Australian Dollar / US Dollar",
        region: "Australia",
        currency: "USD",
        category: "dollar-bloc",
        fetch_kind: AssetFetchKind::FxDaily,
        alpha_symbol: None,
        alpha_base: Some("AUD"),
        alpha_quote: Some("USD"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "nzdusd",
        code: "NZD/USD",
        name: "New Zealand Dollar / US Dollar",
        region: "New Zealand",
        currency: "USD",
        category: "dollar-bloc",
        fetch_kind: AssetFetchKind::FxDaily,
        alpha_symbol: None,
        alpha_base: Some("NZD"),
        alpha_quote: Some("USD"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "usdcad",
        code: "USD/CAD",
        name: "US Dollar / Canadian Dollar",
        region: "Canada",
        currency: "CAD",
        category: "dollar-bloc",
        fetch_kind: AssetFetchKind::FxDaily,
        alpha_symbol: None,
        alpha_base: Some("USD"),
        alpha_quote: Some("CAD"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "usdcnh",
        code: "USD/CNH",
        name: "US Dollar / Offshore Yuan",
        region: "China",
        currency: "CNH",
        category: "asia",
        fetch_kind: AssetFetchKind::FxDaily,
        alpha_symbol: None,
        alpha_base: Some("USD"),
        alpha_quote: Some("CNH"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "usdhkd",
        code: "USD/HKD",
        name: "US Dollar / Hong Kong Dollar",
        region: "Hong Kong",
        currency: "HKD",
        category: "asia",
        fetch_kind: AssetFetchKind::FxDaily,
        alpha_symbol: None,
        alpha_base: Some("USD"),
        alpha_quote: Some("HKD"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "usdsgd",
        code: "USD/SGD",
        name: "US Dollar / Singapore Dollar",
        region: "Singapore",
        currency: "SGD",
        category: "asia",
        fetch_kind: AssetFetchKind::FxDaily,
        alpha_symbol: None,
        alpha_base: Some("USD"),
        alpha_quote: Some("SGD"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "eurgbp",
        code: "EUR/GBP",
        name: "Euro / British Pound",
        region: "Europe",
        currency: "GBP",
        category: "crosses",
        fetch_kind: AssetFetchKind::FxDaily,
        alpha_symbol: None,
        alpha_base: Some("EUR"),
        alpha_quote: Some("GBP"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "eurjpy",
        code: "EUR/JPY",
        name: "Euro / Japanese Yen",
        region: "Global",
        currency: "JPY",
        category: "crosses",
        fetch_kind: AssetFetchKind::FxDaily,
        alpha_symbol: None,
        alpha_base: Some("EUR"),
        alpha_quote: Some("JPY"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "gbpjpy",
        code: "GBP/JPY",
        name: "British Pound / Japanese Yen",
        region: "Global",
        currency: "JPY",
        category: "crosses",
        fetch_kind: AssetFetchKind::FxDaily,
        alpha_symbol: None,
        alpha_base: Some("GBP"),
        alpha_quote: Some("JPY"),
        alpha_market: None,
        alpha_function: None,
        finnhub_symbol: None,
    },
];

pub(crate) const FUTURES_DEFINITIONS: &[AssetDefinition] = &[
    AssetDefinition {
        id: "wti",
        code: "WTI",
        name: "WTI Crude Oil",
        region: "Global",
        currency: "USD",
        category: "energy",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: Some("WTI"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "brent",
        code: "BRENT",
        name: "Brent Crude Oil",
        region: "Global",
        currency: "USD",
        category: "energy",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: Some("BRENT"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "natgas",
        code: "NATGAS",
        name: "Natural Gas",
        region: "Global",
        currency: "USD",
        category: "energy",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: Some("NATURAL_GAS"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "copper",
        code: "COPPER",
        name: "Copper",
        region: "Global",
        currency: "USD",
        category: "metals",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: Some("COPPER"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "aluminum",
        code: "ALUMINUM",
        name: "Aluminum",
        region: "Global",
        currency: "USD",
        category: "metals",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: Some("ALUMINUM"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "wheat",
        code: "WHEAT",
        name: "Wheat",
        region: "Global",
        currency: "USD",
        category: "grains",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: Some("WHEAT"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "corn",
        code: "CORN",
        name: "Corn",
        region: "Global",
        currency: "USD",
        category: "grains",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: Some("CORN"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "cotton",
        code: "COTTON",
        name: "Cotton",
        region: "Global",
        currency: "USD",
        category: "softs",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: Some("COTTON"),
        finnhub_symbol: None,
    },
    AssetDefinition {
        id: "coffee",
        code: "COFFEE",
        name: "Coffee",
        region: "Global",
        currency: "USD",
        category: "softs",
        fetch_kind: AssetFetchKind::CommoditySeries,
        alpha_symbol: None,
        alpha_base: None,
        alpha_quote: None,
        alpha_market: None,
        alpha_function: Some("COFFEE"),
        finnhub_symbol: None,
    },
];

pub(crate) fn supported_assets() -> &'static [&'static str] {
    &["stocks", "etf", "crypto", "forex", "futures"]
}

pub(crate) fn asset_category_ids(asset: &str) -> Option<&'static [&'static str]> {
    match asset {
        "stocks" => Some(STOCK_CATEGORY_IDS),
        "etf" => Some(ETF_CATEGORY_IDS),
        "crypto" => Some(CRYPTO_CATEGORY_IDS),
        "forex" => Some(FOREX_CATEGORY_IDS),
        "futures" => Some(FUTURES_CATEGORY_IDS),
        _ => None,
    }
}

pub(crate) fn definitions_for_asset(asset: &str) -> Option<&'static [AssetDefinition]> {
    match asset {
        "stocks" => Some(STOCK_DEFINITIONS),
        "etf" => Some(ETF_DEFINITIONS),
        "crypto" => Some(CRYPTO_DEFINITIONS),
        "forex" => Some(FOREX_DEFINITIONS),
        "futures" => Some(FUTURES_DEFINITIONS),
        _ => None,
    }
}

pub(crate) fn category_counts(asset: &str) -> Vec<AssetCategoryCount> {
    let Some(categories) = asset_category_ids(asset) else {
        return Vec::new();
    };
    let Some(definitions) = definitions_for_asset(asset) else {
        return Vec::new();
    };

    categories
        .iter()
        .map(|category| AssetCategoryCount {
            id: (*category).to_string(),
            total: definitions
                .iter()
                .filter(|definition| definition.category == *category)
                .count(),
        })
        .collect()
}
