/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as FuturesRouteImport } from './routes/futures'
import { Route as EtfRouteImport } from './routes/etf'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as CryptoRouteImport } from './routes/crypto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as MarketKindItemIdRouteImport } from './routes/market.$kind.$itemId'

const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const FuturesRoute = FuturesRouteImport.update({
  id: '/futures',
  path: '/futures',
  getParentRoute: () => rootRouteImport,
} as any)
const EtfRoute = EtfRouteImport.update({
  id: '/etf',
  path: '/etf',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoRoute = CryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketKindItemIdRoute = MarketKindItemIdRouteImport.update({
  id: '/market/$kind/$itemId',
  path: '/market/$kind/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crypto': typeof CryptoRoute
  '/custom': typeof CustomRoute
  '/etf': typeof EtfRoute
  '/futures': typeof FuturesRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/stocks': typeof StocksRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/market/$kind/$itemId': typeof MarketKindItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crypto': typeof CryptoRoute
  '/custom': typeof CustomRoute
  '/etf': typeof EtfRoute
  '/futures': typeof FuturesRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/stocks': typeof StocksRoute
  '/dashboard': typeof DashboardIndexRoute
  '/market/$kind/$itemId': typeof MarketKindItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crypto': typeof CryptoRoute
  '/custom': typeof CustomRoute
  '/etf': typeof EtfRoute
  '/futures': typeof FuturesRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/stocks': typeof StocksRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/market/$kind/$itemId': typeof MarketKindItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crypto'
    | '/custom'
    | '/etf'
    | '/futures'
    | '/products'
    | '/settings'
    | '/stocks'
    | '/dashboard/'
    | '/market/$kind/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crypto'
    | '/custom'
    | '/etf'
    | '/futures'
    | '/products'
    | '/settings'
    | '/stocks'
    | '/dashboard'
    | '/market/$kind/$itemId'
  id:
    | '__root__'
    | '/'
    | '/crypto'
    | '/custom'
    | '/etf'
    | '/futures'
    | '/products'
    | '/settings'
    | '/stocks'
    | '/dashboard/'
    | '/market/$kind/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CryptoRoute: typeof CryptoRoute
  CustomRoute: typeof CustomRoute
  EtfRoute: typeof EtfRoute
  FuturesRoute: typeof FuturesRoute
  ProductsRoute: typeof ProductsRoute
  SettingsRoute: typeof SettingsRoute
  StocksRoute: typeof StocksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  MarketKindItemIdRoute: typeof MarketKindItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futures': {
      id: '/futures'
      path: '/futures'
      fullPath: '/futures'
      preLoaderRoute: typeof FuturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etf': {
      id: '/etf'
      path: '/etf'
      fullPath: '/etf'
      preLoaderRoute: typeof EtfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto': {
      id: '/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$kind/$itemId': {
      id: '/market/$kind/$itemId'
      path: '/market/$kind/$itemId'
      fullPath: '/market/$kind/$itemId'
      preLoaderRoute: typeof MarketKindItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CryptoRoute: CryptoRoute,
  CustomRoute: CustomRoute,
  EtfRoute: EtfRoute,
  FuturesRoute: FuturesRoute,
  ProductsRoute: ProductsRoute,
  SettingsRoute: SettingsRoute,
  StocksRoute: StocksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  MarketKindItemIdRoute: MarketKindItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
